export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR';

export const FETCH_POSTS_AMOUNT = 'FETCH_POSTS_AMOUNT';
export const FETCH_POSTS_AMOUNT_SUCCESS = 'FETCH_POSTS_AMOUNT_SUCCESS';
export const FETCH_POSTS_AMOUNT_ERROR = 'FETCH_POSTS_AMOUNT_ERROR';

export const SET_POSTS_AMOUNT = 'SET_POSTS_AMOUNT';
export const SET_PAGE = 'SET_PAGE';
export const SET_PAGINATION = 'SET_PAGINATION';
